In [2]:
import torch
import torch.nn as nn
print(torch.__version__)


2.1.0+cu121


In [26]:
# 1. Four Neurons ( 3 input (3,1) and 4 neurons)

# Define your network
net = nn.Linear(3, 4) # Single input feature (3,1) and four neuron

# Manually set weights --> # 4*3 weight matrix
weights = torch.tensor([[1.0, -1.0, 1.0],  # Neuron 1 weights
                        [1.0, 1.0, 0.0],  # Neuron 2 weights
                        [0.0, 1.0, 1.0],  # Neuron 3 weights
                        [1.0, 0.0, 1.0]]) # Neuron 4 weights

bias = torch.tensor([-5.0, 0.0, 1.0, -2.0]) # (4*1) bias --> in pytorch bias element represented as linear 1D vector

# Assign weights and biases
net.weight.data = weights
net.bias.data = bias

# Print the modified network
print('network structure:')
print(net)
print('\nWeight of the network:')
print(net.weight)
print('\nBias of the network:')
print(net.bias)

# Now lets create the input vector x
x = torch.tensor([[2.0, 1.0, 3.0]])
print("input = x :\n ",x)
z = torch.matmul(net.weight,x.t()) + b.view(4,1); # b.view(4,1)
print('w x + b :\n',z)

# Applying ReLU activation
output = torch.relu(z)
print('ReLU applied to w x + b:\n', output)

network structure:
Linear(in_features=3, out_features=4, bias=True)

Weight of the network:
Parameter containing:
tensor([[ 1., -1.,  1.],
        [ 1.,  1.,  0.],
        [ 0.,  1.,  1.],
        [ 1.,  0.,  1.]], requires_grad=True)

Bias of the network:
Parameter containing:
tensor([-5.,  0.,  1., -2.], requires_grad=True)
input = x :
  tensor([[2., 1., 3.]])
w x + b :
 tensor([[-1.],
        [ 3.],
        [ 5.],
        [ 3.]], grad_fn=<AddBackward0>)
ReLU applied to w x + b:
 tensor([[0.],
        [3.],
        [5.],
        [3.]], grad_fn=<ReluBackward0>)
