In [ ]:
import torch
import torch.nn as nn
print(torch.__version__)

2.1.0+cu121


In [7]:
import torch
import torch.nn as nn

# Define your network architecture
class OneHiddenLayerNetwork(nn.Module):
    def __init__(self):
        super(OneHiddenLayerNetwork, self).__init__()
        self.fc1 = nn.Linear(3, 4)  # Input layer to hidden layer
        self.fc2 = nn.Linear(4, 2)  # Hidden layer to output layer

        # Manually set weights and biases
        self.fc1.weight.data = torch.tensor([[1.0, -1.0, 1.0],   # Weights from input to hidden layer
                                             [1.0, 1.0, 0.0],
                                             [0.0, 1.0, 1.0],
                                             [1.0, 0.0, 1.0]])
        self.fc1.bias.data = torch.tensor([-5.0, 0.0, 1.0, -2.0])  # Biases for hidden layer

        self.fc2.weight.data = torch.tensor([[1.0, 1.0, -1.0, 0.0],
                                             [0.0, 0.0, 1.0, -1.0]])  # weights for the layer 2 ( 2*4)
        self.fc2.bias.data = torch.tensor([0.0, 1.0])      # bias for output layer (2*1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))  # Applying ReLU activation after the first layer
        x = torch.relu(self.fc2(x))  # Output layer with relu activation
        return x

# Create an instance of the network
net = OneHiddenLayerNetwork()

# Print the weights and biases of each layer
print('Weights and biases of each layer:')
print('Weight of the first layer:')
print(net.fc1.weight.data)
print('Bias of the first layer:')
print(net.fc1.bias.data)
print('Weight of the second layer:')
print(net.fc2.weight.data)
print('Bias of the second layer:')
print(net.fc2.bias.data)
# Print the modified network
print('Network structure:')
print(net)

# Now let's create the input vector x
x = torch.tensor([[2.0, 1.0, 3.0]])

# Forward pass through the first layer
wx_plus_b_fc1 = torch.matmul(net.fc1.weight.data, x.t()) + net.fc1.bias.data.view(4, 1)
print('wx + b for the first layer:\n', wx_plus_b_fc1)

# Applying ReLU activation to wx + b for the first layer
relu_output = torch.relu(wx_plus_b_fc1)
print('ReLU applied to wx + b for the first layer:\n', relu_output)

# Forward pass through the second layer
wx_plus_b_fc2 = torch.matmul(net.fc2.weight.data, relu_output) + net.fc2.bias.data.view(2, 1)
print('wx + b for the second layer:\n', wx_plus_b_fc2)

# Applying ReLU activation to wx + b for the first layer
relu_output_fc2 = torch.relu(wx_plus_b_fc2)
print('ReLU applied to wx + b for the first layer:\n', relu_output_fc2)

# # Forward pass through the network
output = net(x)
print('Output after forward pass through the network:\n', output.view(2,1))


Weights and biases of each layer:
Weight of the first layer:
tensor([[ 1., -1.,  1.],
        [ 1.,  1.,  0.],
        [ 0.,  1.,  1.],
        [ 1.,  0.,  1.]])
Bias of the first layer:
tensor([-5.,  0.,  1., -2.])
Weight of the second layer:
tensor([[ 1.,  1., -1.,  0.],
        [ 0.,  0.,  1., -1.]])
Bias of the second layer:
tensor([0., 1.])
Network structure:
OneHiddenLayerNetwork(
  (fc1): Linear(in_features=3, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=2, bias=True)
)
wx + b for the first layer:
 tensor([[-1.],
        [ 3.],
        [ 5.],
        [ 3.]])
ReLU applied to wx + b for the first layer:
 tensor([[0.],
        [3.],
        [5.],
        [3.]])
wx + b for the second layer:
 tensor([[-2.],
        [ 3.]])
ReLU applied to wx + b for the first layer:
 tensor([[0.],
        [3.]])
Output after forward pass through the network:
 tensor([[0.],
        [3.]], grad_fn=<ViewBackward0>)


torch.Size([1, 2])