In [8]:
# Ex5: Seven Layers aka Multilayered Perceptron (MLP)

import torch
import torch.nn as nn

# Define your network architecture
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.fc1 = nn.Linear(3, 5)  # Layer1
        self.fc2 = nn.Linear(5, 2)  # layer2
        self.fc3 = nn.Linear(2,3)   # Layer3
        self.fc4 = nn.Linear(3,2)   # layer4
        self.fc5 = nn.Linear(2,2)
        self.fc6 = nn.Linear(2,2)
        self.fc7 = nn.Linear(2,1)   # output layer

        # Manually set weights and biases
        self.fc1.weight.data = torch.tensor([[0.0, 0.0, 1.0],   # Weights from input to hidden layer ( 5*3)
                                             [0.0, 1.0, 0.0],
                                             [1.0, 0.0, 0.0],
                                             [1.0, 1.0, 0.0],
                                             [0.0, 1.0, 1.0]])
        self.fc1.bias.data = torch.tensor([0.0, 0.0, 0.0, 0.0, 0.0])  # Biases for hidden layer

        self.fc2.weight.data = torch.tensor([[1.0, 1.0, -1.0, 0.0, 0.0],
                                             [0.0, 0.0, 1.0, 1.0, -1.0]])  # weights for the layer 2 ( 2*5)
        self.fc2.bias.data = torch.tensor([0.0, 0.0])      # bias for output layer (2*1)
        self.fc3.weight.data = torch.tensor([[1.0,1.0],
                                            [1.0,-1.0],
                                            [1.0,2.0]]) # 3*2
        self.fc3.bias.data = torch.tensor([0.0,0.0,0.0]) # 3*1
        self.fc4.weight.data = torch.tensor([[1.0,-1.0,0.0],
                                            [0.0,-1.0,1.0]]) # 2*3
        self.fc4.bias.data = torch.tensor([0.0,0.0]) # 2*1
        self.fc5.weight.data = torch.tensor([[0.0,1.0],
                                            [1.0,0.0]]) # 2*2
        self.fc5.bias.data = torch.tensor([0.0,0.0]) # 2*1
        self.fc6.weight.data = torch.tensor([[1.0,-1.0],
                                            [1.0,1.0]]) # 2*2
        self.fc6.bias.data = torch.tensor([0.0,0.0]) # 2*1
        self.fc7.weight.data = torch.tensor([[1.0,-1.0]]) # 1*2
        self.fc7.bias.data = torch.tensor([0.0]) # 1*1


    def forward(self, x):
        x = torch.relu(self.fc1(x))  # Applying ReLU activation after the first layer
        x = torch.relu(self.fc2(x))  # layer2 activation
        x = torch.relu(self.fc3(x))
        x = torch.relu(self.fc4(x))
        x = torch.relu(self.fc5(x))
        x = torch.relu(self.fc6(x))
        x = torch.relu(self.fc7(x))
        return x

# Create an instance of the network
net = MLP()

# Print the weights and biases of each layer
print('Weights and biases of each layer:')
print('Weight of the first layer:')
print(net.fc1.weight.data.shape)
print('Bias of the first layer:')
print(net.fc1.bias.data.shape)
print('Weight of the second layer:')
print(net.fc2.weight.data)
print('Bias of the second layer:')
print(net.fc2.bias.data)
# Print the modified network
print('Network structure:')
print(net)

# Now let's create the input vector x for a batch of 2 inputs
x = torch.tensor([[3.0, 4.0,5.0],
                  [5.0,4.0, 3.0]])
print(x.shape)
# Forward pass through the first layer
wx_plus_b_fc1 = torch.matmul(x, net.fc1.weight.data.t()) + net.fc1.bias.data
print('# Now let\'s create the input vector x for a batch of 3 inputs')
print('x:', x)
print('wx + b for the first layer:\n', wx_plus_b_fc1.t())

# Applying ReLU activation to wx + b for the first layer
relu_output = torch.relu(wx_plus_b_fc1)
print('ReLU applied to wx + b for the first layer:\n', relu_output.t())

# Forward pass through the second layer
wx_plus_b_fc2 = torch.matmul(relu_output, net.fc2.weight.data.t()) + net.fc2.bias.data
print('wx + b for the second layer:\n', wx_plus_b_fc2.t())

# Applying ReLU activation to wx + b for the second layer
relu_output_fc2 = torch.relu(wx_plus_b_fc2)
print('ReLU applied to wx + b for the second layer:\n', relu_output_fc2.t())

# Forward pass through the network
output = net(x)
print('Output after forward pass through the network:\n', output.t())

Weights and biases of each layer:
Weight of the first layer:
torch.Size([5, 3])
Bias of the first layer:
torch.Size([5])
Weight of the second layer:
tensor([[ 1.,  1., -1.,  0.,  0.],
        [ 0.,  0.,  1.,  1., -1.]])
Bias of the second layer:
tensor([0., 0.])
Network structure:
MLP(
  (fc1): Linear(in_features=3, out_features=5, bias=True)
  (fc2): Linear(in_features=5, out_features=2, bias=True)
  (fc3): Linear(in_features=2, out_features=3, bias=True)
  (fc4): Linear(in_features=3, out_features=2, bias=True)
  (fc5): Linear(in_features=2, out_features=2, bias=True)
  (fc6): Linear(in_features=2, out_features=2, bias=True)
  (fc7): Linear(in_features=2, out_features=1, bias=True)
)
torch.Size([2, 3])
# Now let's create the input vector x for a batch of 3 inputs
x: tensor([[3., 4., 5.],
        [5., 4., 3.]])
wx + b for the first layer:
 tensor([[5., 3.],
        [4., 4.],
        [3., 5.],
        [7., 9.],
        [9., 7.]])
ReLU applied to wx + b for the first layer:
 tensor([[5.